version: "3.8"

services:
  server:
    image: starterkitapi
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=${APP_ENV}
    command: sh -c "/app/entrypoint.sh"
